---
version: '3.8'

volumes:
  ai-interview-postgres-db:

networks:
  ai-interview-proxy:
  proxy:
    external: true

services:
  ai-interview-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-interview-backend
    networks:
      - ai-interview-proxy
      - proxy
    ports: [5000:5000] # disable in production
    env_file: .env
    depends_on:
      - postgres
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: [ 'node', 'dist/index.js']

  postgres:
    container_name: ai-interview-postgres
    image: postgres:16-alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ai-interview-postgres-db:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ai-interview-proxy
    # ports: [5432:5432]