export const jobRoles = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Mobile Developer",
  "QA Engineer",
  "Cloud Engineer",
  "Security Engineer",
  "System Administrator",
  "Tech Lead",
  "Engineering Manager",
  "Data Engineer",
  "Product Manager",
  "UI/UX Designer",
  "Database Administrator",
  "Blockchain Developer",
  "Site Reliability Engineer",
  "Network Engineer",
  "IT Support Specialist",
  "Solutions Architect",
  "AI Researcher",
  "Business Analyst",
  "Embedded Systems Engineer",
  "Game Developer",
  "Robotics Engineer",
  "IoT Developer",
  "Software Architect",
  "Scrum Master",
  "Chief Technology Officer (CTO)",
  "Data Analyst",
  "Technical Writer",
  "Penetration Tester",
  "VR/AR Developer",
  "Hardware Engineer",
  "No-Code/Low-Code Developer",
  "DevRel (Developer Relations Engineer)",
  "Cybersecurity Analyst",
  "Enterprise Architect",
  "Release Manager",
  "Software Test Engineer",
];

export const difficultyLevel = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
};
