export const envs = {
  ENVIRONMENT: process.env["ENVIRONMENT"],
  ALLOWED_ORIGINS: process.env["ALLOWED_ORIGINS"],
  SERVER_KEY: process.env["SERVER_KEY"],
  PORT: process.env["PORT"],
  MAIL_HOST: process.env["MAIL_HOST"],
  MAIL_USER: process.env["MAIL_USER"],
  MAIL_PASS: process.env["MAIL_PASS"],
  JWT_SECRET: process.env["JWT_SECRET"],
  TOKEN_NAME: process.env["TOKEN_NAME"],
  FOLDER_NAME: process.env["FOLDER_NAME"],
  CLOUD_NAME: process.env["CLOUD_NAME"],
  API_KEY: process.env["API_KEY"],
  API_SECRET: process.env["API_SECRET"],
  GEMINI_API_KEY: process.env["GEMINI_API_KEY"],
  POSTGRES_HOST: process.env["POSTGRES_HOST"],
  POSTGRES_USER: process.env["POSTGRES_USER"],
  POSTGRES_DB: process.env["POSTGRES_DB"],
  POSTGRES_PASSWORD: process.env["POSTGRES_PASSWORD"],
};
