---
version: '3.8'

volumes:
  aiinterview-redis-data:
    name: aiinterview-redis-data
  aiinterview-postgres-db:
    name: aiinterview-postgres-db

networks:
  aiinterview-backend-proxy:
    external: true

services:
  aiinterview-redis:
    image: redis/redis-stack-server:latest
    container_name: aiinterview-redis
    env_file:
      - .env
    volumes:
      - aiinterview-redis-data:/data
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
    # ports: ["6379:6379"]
    networks:
      - aiinterview-backend-proxy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  aiinterview-postgres:
    container_name: aiinterview-postgres
    image: postgres:16-alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - aiinterview-postgres-db:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped # Ensure the container restarts unless manually stopped
    networks:
      - aiinterview-backend-proxy
    # ports: [5432:5432]